name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build with Maven
        # run: mvn clean package -DskipTests
        run: mvn clean package

      - name: Run all tests
        run: mvn test